# Generated by Django 5.2.4 on 2025-07-18 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='category',
            field=models.CharField(choices=[('sleep', 'Sleep'), ('focus', 'Focus'), ('emotional_healing', 'Emotional Healing'), ('nature', 'Nature'), ('instrumental', 'Instrumental')], default='instrumental', max_length=20),
        ),
        migrations.CreateModel(
            name='FavoritePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('music', models.ManyToManyField(blank=True, related_name='favorited_by', to='music.music')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_playlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
