# Generated by Django 5.2.4 on 2025-07-10 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='workbooks/banners/'),
        ),
        migrations.AddField(
            model_name='workbook',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workbook',
            name='pdf_file',
            field=models.FileField(upload_to='workbooks/pdfs/'),
        ),
    ]
