# Generated by Django 5.2.4 on 2025-07-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbook', '0003_category_workbook_category_favoriteworkbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
