# Generated by Django 5.2.4 on 2025-07-23 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
