# Generated by Django 5.2.4 on 2025-07-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mood_tracker', '0002_alter_moodentry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('neutral', 'Neutral'), ('Angry', 'Angry'), ('Anxious', 'Anxious')], max_length=20),
        ),
    ]
