# Generated by Django 5.2.4 on 2025-07-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.TextField(blank=True, default='', help_text="List features line by line, e.g. use '\\n' for new line."),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
