# Generated by Django 5.2.4 on 2025-07-23 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_dailytaskcompletion_delete_userinteraction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affirmation',
            name='completed_by',
            field=models.ManyToManyField(blank=True, related_name='completed_affirmations', to=settings.AUTH_USER_MODEL),
        ),
    ]
