# Generated by Django 5.2.4 on 2025-07-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_affirmation_completed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytaskcompletion',
            name='breathing_completed',
        ),
        migrations.AddField(
            model_name='dailytaskcompletion',
            name='breathing_exercise_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
