# Generated by Django 5.2.4 on 2025-07-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_dailytaskcompletion_breathing_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affirmation',
            name='suggested_resource',
        ),
        migrations.RemoveField(
            model_name='breathingexercise',
            name='suggested_resource',
        ),
        migrations.AlterUniqueTogether(
            name='selfcaretask',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='selfcaretask',
            name='user',
        ),
        migrations.AlterField(
            model_name='affirmation',
            name='date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='ProgressGoal',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.DeleteModel(
            name='SelfCareTask',
        ),
    ]
